const User = require('./User')
const Role = require('./Role')
const Class = require('./Class')
const Subject = require('./Subject')
const Chapter = require('./Chapter')
const QuestionBank = require('./QuestionBank')
const Content = require('./Content')
const Quiz = require('./Quiz')
const Gallery=require("./Gallery")
const News=require("./News")
const Headline=require("./Headline")
const Tenders=require("./Tenders")
const Jobs=require("./Jobs")
const Downloads=require("./Downloads")
const Links=require("./Links")
const Slider=require("./Slider")
const Videos=require("./Videos")
const Locations=require("./Locations")
const Team=require("./Team")
const SocialLinks=require("./SocialLinks")
const Components=require("./Components")
module.exports = {
    User, Role, Class, Subject, Chapter, QuestionBank, Content, Quiz,Gallery,News, Headline, Tenders,Jobs,Downloads, 
    Links, Slider,Videos, Locations, Team, SocialLinks, Components
}